# Generated by custom migration for teacher ForeignKey conversion

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_teacher_names(apps, schema_editor):
    """
    Copy old teacher CharField data to teacher_name before converting to ForeignKey.
    """
    Section = apps.get_model('academics', 'Section')
    
    # Copy teacher string to teacher_name
    for section in Section.objects.all():
        section.teacher_name = getattr(section, '_teacher_old', '')
        section.save(update_fields=['teacher_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Rename old teacher field temporarily
        migrations.RenameField(
            model_name='section',
            old_name='teacher',
            new_name='_teacher_old',
        ),
        
        # Step 2: Add teacher_name field
        migrations.AddField(
            model_name='section',
            name='teacher_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Display name for teacher (auto-populated from user)',
                max_length=128
            ),
            preserve_default=False,
        ),
        
        # Step 3: Copy old data to teacher_name
        migrations.RunPython(
            preserve_teacher_names,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Step 4: Add new teacher ForeignKey field
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                help_text='Faculty user assigned to teach this section',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sections',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Step 5: Remove old teacher field
        migrations.RemoveField(
            model_name='section',
            name='_teacher_old',
        ),
        
        # Step 6: Remove old unique_together and add new one
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'term', 'teacher')},
        ),
    ]
