"""Jazzmin admin theme configuration for FMU SIMS."""

JAZZMIN_SETTINGS = {
    "site_title": "FMU SIMS Admin",
    "site_header": "FMU Student Information System",
    "site_brand": "FMU SIMS",
    "welcome_sign": "Manage students, courses, attendance, and results",
    "site_logo": "img/fmu_logo.png",
    "login_logo": "img/fmu_logo.png",
    "site_logo_classes": "img-circle",
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Docs", "url": "/api/docs/"},
        {"name": "ReDoc", "url": "/api/redoc/"},
        {"model": "auth.User"},
    ],
    "order_with_respect_to": [
        "admissions",
        "academics",
        "attendance",
        "results",
        "assessments",
        "enrollment",
        "requests",
        "transcripts",
        "audit",
        "auth",
    ],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "admissions.student": "fas fa-id-badge",
        "academics.course": "fas fa-book",
        "academics.section": "fas fa-columns",
        "academics.program": "fas fa-graduation-cap",
        "attendance.attendance": "fas fa-user-check",
        "results.result": "fas fa-poll",
        "assessments.assessment": "fas fa-tasks",
        "assessments.assessmentscore": "fas fa-clipboard-check",
        "enrollment.enrollment": "fas fa-user-plus",
        "requests.request": "fas fa-envelope",
        "transcripts.transcript": "fas fa-file-alt",
        "audit.auditlog": "fas fa-history",
    },
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "admissions.student": "collapsible",
        "academics.course": "tabs",
    },
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-primary",
    "footer_fixed": False,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "actions_sticky_top": True,
}
