x 
name: Diagnose app_label wiring
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework
      - name: Run diagnostics
        run: |
          python tools/diagnose_app_labels.py
